rees46/ios-sdk

REES46/Classes/PersonalizationSDK.swift
REES46/Classes/SimplePersonalizationSDK.swift

issue: https://github.com/rees46/development/issues/428

added parameter "platform" for method setPushTokenNotification

---

REES46/Classes/Extensions/NetworkStatus/SdkGlobalHelper.swift
REES46/Classes/Extensions/SdkConfiguration/SdkConfiguration.swift
REES46/Classes/Model/Stories.swift
REES46/Classes/Stories/StoryViewController/CollectionViewCell/StoryCollectionViewCell.swift
REES46/Classes/Stories/StoryViewController/StoryViewController.swift
REES46/Classes/Stories/TextBlockView/TextBlockConfiguration/TBSubConfigurations/TBAppearanceConfiguration.swift
REES46/Classes/Stories/TextBlockView/TextBlockConfiguration/TBSubConfigurations/TBFontConfiguration.swift
REES46/Classes/Stories/TextBlockView/TextBlockConfiguration/TBSubConfigurations/TBTextConfiguration.swift
REES46/Classes/Stories/TextBlockView/TextBlockConfiguration/TexBlockConfiguration.swift
REES46/Classes/Stories/TextBlockView/TextBlockConstants.swift
REES46/Classes/Stories/TextBlockView/TextBlockView.swift
Shared/ColorExtensions.swift

moved color and opacity configuration from model,
changed position of text block objects to be equal to recieved data from server, changed font configuration from UIFontDescriptor to using UIFont(), fixed text block's label alignment

fix: fixed text block object model and configuring view

---

DemoApp/REES46Demo/AppDelegate.swift
REES46/Classes/PersonalizationSDK.swift
REES46/Classes/SimplePersonalizationSDK.swift

добавил полную версию метода full_wish для iOS SDK
- [https://github.com/rees46/planning/issues/426](https://github.com/rees46/planning/issues/426)

feat: created full_wish method for syncing favorites

---

REES46/Classes/SimplePersonalizationSDK.swift

* https://github.com/rees46/planning/issues/30

feat: Add support for fashionSize, fashionColor, and barcode

---

DemoApp/REES46.xcodeproj/xcshareddata/xcschemes/REES46Demo.xcscheme
REES46/Classes/SimplePersonalizationSDK.swift
REES46/Classes/Stories/StoryViewController/CollectionViewCell/StoryCollectionViewCell.swift
REES46/Classes/Stories/StoryViewController/StoryViewController.swift

* https://github.com/rees46/planning/issues/1228

feat: Add closing stories with animation by slide button click

---

.github/workflows/publish.yaml

Feat: github

---

REES46.podspec

- https://github.com/rees46/planning/issues/1751

chore: Bump podspec version to match with persona

---

REES46/Classes/Stories/StoriesView.swift

- https://github.com/rees46/development/issues/1845

feat: add stories callback

---

REES46/Classes/Extensions/NetworkStatus/NetworkStatus.swift
REES46/Classes/InAppNotification/view/component/button/DialogActionButton.swift
REES46/Classes/InAppNotification/view/component/button/DialogButtonClose.swift
REES46/Classes/InAppNotification/view/component/dialog/FullScreenDialog.swift
REES46/Classes/InAppNotification/view/component/image/DialogImageVeiw.swift
REES46/Classes/InAppNotification/view/component/text/DialogText.swift
REES46/Classes/Regex/EmailValidator.swift
REES46/Classes/Regex/Helper/RegexHelper.struct.swift
REES46/Classes/Regex/PhoneValidator.swift
REES46/Classes/Resources/AppColors.struct.swift
REES46/Classes/Resources/AppDimensions.struct.swift
REES46/Classes/Sdk/Extensions/Popup.extension.swift
REES46/Classes/Sdk/Model/Popup.struct.swift
REES46/Classes/Sdk/Model/PopupActions.struct.swift
REES46/Classes/Sdk/Model/PopupComponents.struct.swift
REES46/Classes/Stories/StoryViewController/SearchWidget/Extensions/Bundle.swift
REES46/Classes/Stories/StoryViewController/SearchWidget/Extensions/SearchResultsView.extension.swift
REES46/Classes/Stories/StoryViewController/SearchWidget/Extensions/UIView.swift
REES46/Classes/Stories/StoryViewController/SearchWidget/Protocol/SearchFilterCheckBoxViewDelegate.protocol.swift

https://github.com/rees46/development/issues/2569
так как технодом написал, что ошибка в импортах, добавил импорты

Fix: sdk build fix

---

REES46/Classes/Sdk/impl/SimplePersonalizationSDK.swift

- https://github.com/rees46/development/issues/2251

fix(suggest): fix path

---

.github/workflows/sync.yaml

feat(github): target repo to inputs

---

.github/workflows/sync.yaml
REES46.podspec

for https://github.com/rees46/development/issues/2714
merge after https://github.com/rees46/workflow/pull/276
proof https://github.com/PersonaClick/ios-sdk/pull/94
- ссылались на старый воркфлоу, который не использовал новые экшены
- переписал воркфлоу, задействую новые экшены
- в текущей репе - прокидываю новые переменные, новые replacements

refactor(github): reusable ios synchronization

---

REES46/Classes/Sdk/impl/SimplePersonalizationSDK.swift

**Таска:**
- https://github.com/rees46/development/issues/2789
**Пруфы:**
Если не передавать parentViewController при ините ничего не крашится (даже если при ините приходит попап)

Fix parentViewController in init

---

.github/workflows/sync.yaml

for https://github.com/rees46/development/issues/2714
- demo-app не синкался, изза этого ошибка чеков в персоне

refactor(github): rm demo app from sync ignore

---

.github/workflows/constants/replacements.yml
.github/workflows/publish.yaml
.github/workflows/version.yaml
.releaserc.yml

for: https://github.com/rees46/development/issues/2534
- правки триггера
- правки replacements

refactor(github): workflow

---

REES46.podspec

for https://github.com/rees46/development/issues/2534
- триггер воркфлоу. ошибся в файлах

feat(common): trigger workflow

---

.github/workflows/constants/replacements.yml
.github/workflows/version.yaml
README.md

for https://github.com/rees46/development/issues/2534
merge after https://github.com/rees46/workflow/pull/296
- пробрасываю gh-token to workflow

feat(github): pass gh token to workflow

---

DemoApp/Rees46DemoTests/SdkTest.swift
REES46/Classes/Sdk/protocol/PersonalizationSDK.protocol.swift

**Пруфы:**
<details>
</details>

Default api domain

---

.github/workflows/version.yaml

for https://github.com/rees46/development/issues/2939
- создал versioner-app - https://github.com/organizations/rees46/settings/apps/r46-versioner
- добавил ему минимально необходимые для версионирования права
- поменял нейминги в репозиториях, где версионирование разделено от паблиша
--
proof:
- тестировал изолированно работу с фс и создание пулл-реквеста. комплексно работат только при мердже в мастер. тестировал только в android-sdk, все репозитории работают по одному воркфлоу, расхождений быть не должно
- работа с фс - https://github.com/rees46/android-sdk/actions/runs/15023293960/job/42219882185
- сделали чекаут, прочитали файлы на локалке. скрипт не запустился, потмоучто работает только с push на мастер
- создание ПР - https://github.com/rees46/android-sdk/actions/runs/15034182042/job …

refactor(github): version workflow secrets

---

.github/workflows/publish.yaml

for https://github.com/rees46/development/issues/2939
proof https://github.com/rees46/development/issues/2939#issuecomment-2887708657
- меняю сикреты на новое приложение с минимально необходимыми разрешениями

refactor(github): gh-app secrets

---

.github/workflows/auto-merge-sync-pr.yml.bak
.releaserc.yml

for https://github.com/rees46/development/issues/2939
- отключаю комменты через releaserc
- правки нейминга

refactor(common): releaserc

---

.github/workflows/repo-sync.yml
.github/workflows/version.yaml

https://t.me/c/2243138785/1153/54377

fix(github): reviewer

---

REES46/Classes/Sdk/impl/SimplePersonalizationSDK.swift
REES46/Classes/Sdk/protocol/PersonalizationSDK.protocol.swift
REES46/Classes/Stories/StoryViewController/SearchWidget/Presentation/View/SearchWidgetMainView.swift
REES46/Classes/Tracking/Service/impl/TrackServiceImpl.swift

**Таска:**
- https://t.me/c/2243138785/1153/55324
**Пруфы:**
<details>
</details>

Tracking in app
